### ISSUE TITLE
Add :invalid and :valid psuedo selector to work with html5 validation

### ISSUE THREAD

**Issue by valeness** [yandydotcom/Underwire#24]
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation

**Comment by btn0s** [comment]
Need to work out a way around this behavior.

https://stackoverflow.com/questions/9594088/html5-form-validation-default-invalid-is-this-normal-behavior

**Comment by btn0s** [comment]
Maybe on focus, check validate.
